//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graph.DataLoader
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjacentNode
    {
        public int Id { get; set; }
        public int NodeId { get; set; }
        public int AdjacentId { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Node Node1 { get; set; }
    }
}
