//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graph.UI.GraphInitService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NodeDC", Namespace="http://schemas.datacontract.org/2004/07/Graph.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class NodeDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] AdjacentIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AdjacentIds {
            get {
                return this.AdjacentIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdjacentIdsField, value) != true)) {
                    this.AdjacentIdsField = value;
                    this.RaisePropertyChanged("AdjacentIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GraphInitService.IGraphInitService")]
    public interface IGraphInitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphInitService/GetUndirectedGraph", ReplyAction="http://tempuri.org/IGraphInitService/GetUndirectedGraphResponse")]
        Graph.UI.GraphInitService.NodeDC[] GetUndirectedGraph();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphInitService/GetUndirectedGraph", ReplyAction="http://tempuri.org/IGraphInitService/GetUndirectedGraphResponse")]
        System.Threading.Tasks.Task<Graph.UI.GraphInitService.NodeDC[]> GetUndirectedGraphAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphInitService/GetDirectedGraph", ReplyAction="http://tempuri.org/IGraphInitService/GetDirectedGraphResponse")]
        Graph.UI.GraphInitService.NodeDC[] GetDirectedGraph();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGraphInitService/GetDirectedGraph", ReplyAction="http://tempuri.org/IGraphInitService/GetDirectedGraphResponse")]
        System.Threading.Tasks.Task<Graph.UI.GraphInitService.NodeDC[]> GetDirectedGraphAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraphInitServiceChannel : Graph.UI.GraphInitService.IGraphInitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraphInitServiceClient : System.ServiceModel.ClientBase<Graph.UI.GraphInitService.IGraphInitService>, Graph.UI.GraphInitService.IGraphInitService {
        
        public GraphInitServiceClient() {
        }
        
        public GraphInitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraphInitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphInitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphInitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Graph.UI.GraphInitService.NodeDC[] GetUndirectedGraph() {
            return base.Channel.GetUndirectedGraph();
        }
        
        public System.Threading.Tasks.Task<Graph.UI.GraphInitService.NodeDC[]> GetUndirectedGraphAsync() {
            return base.Channel.GetUndirectedGraphAsync();
        }
        
        public Graph.UI.GraphInitService.NodeDC[] GetDirectedGraph() {
            return base.Channel.GetDirectedGraph();
        }
        
        public System.Threading.Tasks.Task<Graph.UI.GraphInitService.NodeDC[]> GetDirectedGraphAsync() {
            return base.Channel.GetDirectedGraphAsync();
        }
    }
}
